version: '3.8'
services:
  db:
    image: postgis/postgis:14-3.3
    environment:
      POSTGRES_USER: flood
      POSTGRES_PASSWORD: floodpass
      POSTGRES_DB: flooddb
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
